// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: proto/csv_reader.proto

package csvreader

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CSVReaderService_GetCSVData_FullMethodName = "/csvreader.CSVReaderService/GetCSVData"
)

// CSVReaderServiceClient is the client API for CSVReaderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Define the gRPC service
type CSVReaderServiceClient interface {
	GetCSVData(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CSVRow], error)
}

type cSVReaderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCSVReaderServiceClient(cc grpc.ClientConnInterface) CSVReaderServiceClient {
	return &cSVReaderServiceClient{cc}
}

func (c *cSVReaderServiceClient) GetCSVData(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CSVRow], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CSVReaderService_ServiceDesc.Streams[0], CSVReaderService_GetCSVData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, CSVRow]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CSVReaderService_GetCSVDataClient = grpc.ServerStreamingClient[CSVRow]

// CSVReaderServiceServer is the server API for CSVReaderService service.
// All implementations must embed UnimplementedCSVReaderServiceServer
// for forward compatibility.
//
// Define the gRPC service
type CSVReaderServiceServer interface {
	GetCSVData(*Empty, grpc.ServerStreamingServer[CSVRow]) error
	mustEmbedUnimplementedCSVReaderServiceServer()
}

// UnimplementedCSVReaderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCSVReaderServiceServer struct{}

func (UnimplementedCSVReaderServiceServer) GetCSVData(*Empty, grpc.ServerStreamingServer[CSVRow]) error {
	return status.Errorf(codes.Unimplemented, "method GetCSVData not implemented")
}
func (UnimplementedCSVReaderServiceServer) mustEmbedUnimplementedCSVReaderServiceServer() {}
func (UnimplementedCSVReaderServiceServer) testEmbeddedByValue()                          {}

// UnsafeCSVReaderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CSVReaderServiceServer will
// result in compilation errors.
type UnsafeCSVReaderServiceServer interface {
	mustEmbedUnimplementedCSVReaderServiceServer()
}

func RegisterCSVReaderServiceServer(s grpc.ServiceRegistrar, srv CSVReaderServiceServer) {
	// If the following call pancis, it indicates UnimplementedCSVReaderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CSVReaderService_ServiceDesc, srv)
}

func _CSVReaderService_GetCSVData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CSVReaderServiceServer).GetCSVData(m, &grpc.GenericServerStream[Empty, CSVRow]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CSVReaderService_GetCSVDataServer = grpc.ServerStreamingServer[CSVRow]

// CSVReaderService_ServiceDesc is the grpc.ServiceDesc for CSVReaderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CSVReaderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "csvreader.CSVReaderService",
	HandlerType: (*CSVReaderServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetCSVData",
			Handler:       _CSVReaderService_GetCSVData_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/csv_reader.proto",
}
